name: Java CI with Ant

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout project
    
      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - uses: cjmach/setup-autopsy-action@v1
        with:
          version: '4.20.0'

      - name: Run the Ant build target
        run: >-
          ant -noinput -buildfile build.xml
          -Dnbplatform.default.netbeans.dest.dir=${{ github.workspace }}/autopsy
          -Dnbplatform.default.harness.dir=${{ github.workspace }}/autopsy/harness
          build
          